version: '3.8'

services:
    laravel.test:
        build:
            context: './vendor/laravel/sail/runtimes/8.4'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: 'sail-8.4/app'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: ${DB_DATABASE:-weather_alert_app}
            DB_USERNAME: ${DB_USERNAME:-sail}
            DB_PASSWORD: ${DB_PASSWORD:-password}
            MAIL_MAILER: 'smtp'
            MAIL_HOST: 'mailhog'
            MAIL_PORT: 1025
            MAIL_USERNAME: null
            MAIL_PASSWORD: null
            MAIL_ENCRYPTION: null
            MAIL_FROM_ADDRESS: 'alerts@weatherapp.test'
            MAIL_FROM_NAME: 'Weather Alert System'
            

        volumes:
            - '.:/var/www/html'
            - './docker/entrypoint.sh:/entrypoint.sh' 
        networks:
            - sail
        depends_on:
            - mysql
        entrypoint: ["/bin/bash", "/entrypoint.sh"] 
    
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-password}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: ${DB_DATABASE:-weather_alert_app}
            MYSQL_USER: ${DB_USERNAME:-sail}
            MYSQL_PASSWORD: ${DB_PASSWORD:-password}
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s

    scheduler:
        image: sail-8.4/app
        depends_on:
            - laravel.test
        volumes:
            - '.:/var/www/html'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: ${DB_DATABASE:-weather_alert_app}
            DB_USERNAME: ${DB_USERNAME:-sail}
            DB_PASSWORD: ${DB_PASSWORD:-password}
            MAIL_MAILER: 'smtp'
            MAIL_HOST: 'mailhog'
            MAIL_PORT: 1025
            MAIL_USERNAME: null
            MAIL_PASSWORD: null
            MAIL_ENCRYPTION: null
            MAIL_FROM_ADDRESS: 'alerts@weatherapp.test'
            MAIL_FROM_NAME: 'Weather Alert System'
        entrypoint: ["/bin/bash", "/var/www/html/docker/scheduler.sh"]
        networks:
            - sail

    mailhog:
        image: mailhog/mailhog:latest
        ports:
            - 1025:1025    
            - 8025:8025    
        networks:
            - sail
networks:
    sail:
        driver: bridge

volumes:
    sail-mysql:
        driver: local